services:
  number_system_api:
    image: elleined/number-system-api:latest
    container_name: number_system_api
    env_file:
      - .env
    networks:
      - number_system_api_network
networks:
 number_system_api_network:
    name: number_system_api_network
    external: false
    ipam:
      driver: default